'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import AuthGuard from '@/components/AuthGuard'; import AppShell from '@/components/AppShell'; import { getSupabase } from '@/lib/supabase';

export default function NewItem(){const router=useRouter(); const [deps,setDeps]=useState<any[]>([]); const [cats,setCats]=useState<any[]>([]); const [dep,setDep]=useState(''); const [cat,setCat]=useState(''); const [name,setName]=useState(''); const [qty,setQty]=useState(1); const [unit,setUnit]=useState('unit'); const [a1,setA1]=useState(''); const [a2,setA2]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
useEffect(()=>{(async()=>{const s=getSupabase(); const [{data:d},{data:c}]=await Promise.all([s.from('departments').select('*').order('name'),s.from('categories').select('*').order('name')]); setDeps(d||[]);setCats(c||[]);})();},[]);
const selected=cats.find(x=>x.id===cat); const filtered=cats.filter(x=>x.department_id===dep);
const submit=async(e:FormEvent)=>{e.preventDefault(); if(!selected)return; setSaving(true);setError(''); const code='IR-'+Date.now().toString(36).toUpperCase(); const attrs:selected.name==='Fabric'?{Jenis:a1,Berat:a2?`${a2} kg`:''}:selected.name==='Paper'?{'Panjang roll':a1?`${a1} m`:''}:selected.name==='Ink'?{Warna:a1,Jenis:a2}:selected.name==='Thread'?{Warna:a1,Jenis:a2}:{}; Object.keys(attrs).forEach(k=>!(attrs as any)[k]&&delete (attrs as any)[k]); const initial=selected.tracking_mode==='unit'?1:Number(qty); const {data,error}=await getSupabase().from('items').insert({code,name,department_id:dep,category_id:cat,tracking_mode:selected.tracking_mode,status:'IN_STOCK',unit:selected.default_unit||unit,initial_quantity:initial,current_quantity:initial,attributes:attrs}).select('id').single(); if(error){setError(error.message);setSaving(false);return;} router.push('/admin/items?created='+data.id);};
return <AuthGuard adminOnly><AppShell admin><div className="page-head"><div><p className="eyebrow">Admin</p><h1>Daftar Stok</h1></div></div><form className="form card-form" onSubmit={submit}><label>Department<select required value={dep} onChange={e=>{setDep(e.target.value);setCat('')}}><option value="">Pilih department</option>{deps.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Kategori<select required value={cat} onChange={e=>setCat(e.target.value)}><option value="">Pilih kategori</option>{filtered.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Nama item<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Microfiber Putih"/></label>{selected?.name==='Fabric'&&<><label>Jenis kain<input value={a1} onChange={e=>setA1(e.target.value)}/></label><label>Berat roll (kg)<input type="number" step="0.01" value={a2} onChange={e=>setA2(e.target.value)}/></label></>}{selected?.name==='Paper'&&<label>Panjang roll (m)<input type="number" step="0.01" value={a1} onChange={e=>setA1(e.target.value)}/></label>}{['Ink','Thread'].includes(selected?.name)&&<><label>Warna<input value={a1} onChange={e=>setA1(e.target.value)}/></label><label>Jenis<input value={a2} onChange={e=>setA2(e.target.value)}/></label></>}{selected?.tracking_mode==='quantity'&&<><label>Kuantiti awal<input type="number" min="1" required value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Unit<input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="pcs"/></label></>}{error&&<div className="error-box">{error}</div>}<button className="primary" disabled={saving}>{saving?'Menyimpan…':'Daftar & Jana QR'}</button></form></AppShell></AuthGuard>}
