'use client';

import { FormEvent, use, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import AuthGuard from '@/components/AuthGuard';
import AppShell from '@/components/AppShell';
import { getSupabase } from '@/lib/supabase';

export default function ItemPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const router=useRouter(); const [item,setItem]=useState<any>(null); const [project,setProject]=useState(''); const [qty,setQty]=useState(1); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  useEffect(()=>{(async()=>{const s=getSupabase(); let q=s.from('items').select('*,department:departments(name),category:categories(name)').limit(1); q=id.includes('-')&&id.length>20?q.eq('id',id):q.eq('code',decodeURIComponent(id)); const {data}=await q.maybeSingle(); setItem(data); setLoading(false);})();},[id]);
  const checkout=async(e:FormEvent)=>{e.preventDefault(); if(!item)return; setSaving(true);setMessage(''); const {error}=await getSupabase().rpc('checkout_item',{p_item_id:item.id,p_quantity:item.tracking_mode==='unit'?1:Number(qty),p_project:project.trim()||null}); if(error){setMessage(error.message);setSaving(false);return;} setMessage('Keluaran berjaya direkod.'); setTimeout(()=>router.push('/scan'),700);};
  return <AuthGuard><AppShell>{loading?<div className="center"><div className="spinner"/></div>:!item?<div className="empty"><h2>Item tidak ditemui</h2><p>Semak QR atau kod item.</p></div>:<><div className="page-head"><div><p className="eyebrow">{item.code}</p><h1>{item.name}</h1></div><span className={'status '+(item.status==='IN_STOCK'?'ok':'muted')}>{item.status==='IN_STOCK'?'Dalam Stor':'Keluar'}</span></div><section className="detail-card"><dl><div><dt>Department</dt><dd>{item.department?.name}</dd></div><div><dt>Kategori</dt><dd>{item.category?.name}</dd></div>{Object.entries(item.attributes||{}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}{item.tracking_mode==='quantity'&&<div><dt>Baki</dt><dd>{item.current_quantity} {item.unit}</dd></div>}</dl></section>{item.status==='IN_STOCK'?<form className="form checkout" onSubmit={checkout}>{item.tracking_mode==='quantity'&&<label>Jumlah keluar<input type="number" min="1" max={item.current_quantity} value={qty} onChange={e=>setQty(Number(e.target.value))}/></label>}<label>Projek / kegunaan <span className="optional">(jika ada)</span><input value={project} onChange={e=>setProject(e.target.value)} placeholder="Contoh: Baju Sukan SMK ABC"/></label>{message&&<div className={message.includes('berjaya')?'success-box':'error-box'}>{message}</div>}<button className="danger-primary" disabled={saving}>{saving?'Merekod…':'KELUAR'}</button><p className="hint">Selepas disahkan, unit ini dianggap keluar sepenuhnya dari stor.</p></form>:<div className="notice">Item ini telah dikeluarkan dan tidak boleh dikeluarkan kali kedua.</div>}</>}</AppShell></AuthGuard>;
}
